import 'dart:math';

// List of water reminder messages
List<String> waterReminderMessages = [
  "Hydrate your body, it's the best way to show yourself some love. Drink water!",
  "Water is the key to life. Stay refreshed and keep sipping!",
  "Sip, sip, hooray! Your body deserves the best – drink water!",
  "Water is your body's fuel. Keep the engine running smoothly!",
  "Every drop counts. Stay hydrated and conquer the day!",
  "H2O: the original energy drink. Drink up and feel the power!",
  "Water: the source of beauty. Stay radiant, stay hydrated!",
  "Fuel your ambition with water. Stay thirsty for success!",
  "Clear skin, bright eyes, happy heart – all from drinking water!",
  "Stay hydrated, stay unstoppable. You've got this!",
  "Water is the secret ingredient for a healthy and happy life.",
  "Drink water, be awesome. It's that simple.",
  "Water – the ultimate pick-me-up. Take a sip and recharge!",
  "Your body is a temple, and water is the sacred elixir. Drink up!",
  "Don't forget to hydrate. Your body will thank you later!",
  "Water is liquid gold. Treat yourself to a wealth of health!",
  "Stay hydrated, stay shining. You're a star!",
  "Hydration is the key to unlocking your full potential. Drink water!",
  "Don't wait for thirst to strike. Stay ahead – drink water!",
  "Sip by sip, you're building a healthier you. Keep it up!",
  "Cheers to health, happiness, and hydration!",
  "Water is the best anti-aging potion. Drink and stay timeless!",
  "Stay hydrated – your body will thank you with energy and vitality!",
  "A well-hydrated body is a happy body. Keep smiling, keep sipping!",
  "Sweat, hydrate, repeat. The recipe for success!",
  "Life is better when you're hydrated. Drink water and live your best life!",
  "Fuel your workout with water. You're stronger than you think!",
  "Water is the foundation of good health. Drink it in, drink it often!",
  "Hydrate like you mean it. Your body deserves the best!",
  "Water is the ultimate mood booster. Lift your spirits – take a sip!",
  "Water is your body's natural healer. Drink up and feel the magic!",
  "Stay refreshed, stay sharp. Water is your secret weapon!",
  "You're not fully dressed without a water bottle. Hydrate in style!",
  "Water is the catalyst for change. Drink up and transform!",
  "Your body is a garden, and water is the essential nourishment. Water your soul!",
  "Don't just exist – hydrate and thrive! Your body deserves it.",
  "Water: your body's best friend. Treat it right, stay hydrated!",
  "Hydration is the first step towards greatness. Take that step today!",
  "Water is the gift you give to your body. Unwrap it every day!",
  "Keep calm and drink water. It's the simplest form of self-love!",
  "Water: the healthiest habit you can cultivate. Start sipping!",
  "Your body is a work of art. Hydration is the brush that paints it beautiful!",
  "Water is the fuel that propels you forward. Keep the tank full!",
  "Drink water, feel better. It's the ultimate remedy!",
  "Hydration is the cornerstone of well-being. Drink up and thrive!",
  "The more you drink, the more you shine. Stay hydrated!",
  "Water is nature's energy drink. Take a sip and feel the boost!",
  "Your body is 60% water. Keep it happy with a refill!",
  "Water: your ally in the battle against fatigue. Drink up and conquer!",
  "Stay cool, stay hydrated. It's the secret to a happy life!",
  "Water: the elixir of life. Sip your way to vitality!",
  "Hydration is the key to longevity. Drink water and live longer!",
  "Water is the purest form of self-care. Treat yourself daily!",
  "Fuel your brain with water. Stay sharp, stay focused!",
  "Water is the best beauty treatment. Glow from the inside out!",
  "Hydration is a lifestyle. Embrace it, love it, live it!",
  "Water is the essential ingredient for a healthy recipe of life!",
  "Stay hydrated, stay powerful. Water fuels your inner strength!",
  "Water: the original health potion. Brew it, sip it, love it!",
  "Your body deserves a standing ovation. Hydrate and applaud!",
  "Water: the ultimate multitasker. Nourish, refresh, revitalize!",
  "Sip on success, gulp down health. Hydration is the key!",
  "Your body is a canvas. Hydration is the paint that colors it vibrant!",
  "Drink water, unlock your potential. It's the key to greatness!",
  "Water is the elixir of youth. Age gracefully, stay hydrated!",
  "Stay hydrated and sparkle on. You're a diamond!",
  "Your body is a symphony. Water is the conductor that keeps it in harmony!",
];

// Function to get a random water reminder message
String getRandomMessage(arg) {
  Random random = Random();
  int randomIndex = random.nextInt(arg.length);
  return arg[randomIndex];
}
